### ISSUE TITLE
`_tkinter.TclError: bad screen distance "200.0"` (locale float conversion bug in `customtkinter` library)

### ISSUE THREAD

**Issue by SummaCristian** [neurokitti/Arc_Palette#12]
Trying to launch v1.5 in Windows results in the window being instantly closed as soon as it launches.
Launching the script through terminal shows the following stacktrace:

`C:\[...]\Arc_Palette\resources\Windows>run_arc_palette.bat
Traceback (most recent call last):`
 ` File "C:\[...]\Arc_Palette\main.py", line 262, in <module>
    add_tab(arc_api)`
 ` File "C:\[...]\Arc_Palette\main.py", line 219, in add_tab
    slider = ctk.CTkSlider(master=slider_alpha_frame, from_=0, to=100, command=slider_set_alpha)`        `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "C:[...]\Arc_Palette\.venv\Lib\site-packages\customtkinter\windows\widgets\ctk_slider.py", line 92, in __init__
    self._canvas = CTkCanvas(master=self,`
`                   ^^^^^^^^^^^^^^^^^^^^^^`
`  File "C:[...]\Arc_Palette\.venv\Lib\site-packages\customtkinter\windows\widgets\core_rendering\ctk_canvas.py", line 31, in __init__`
`    super().__init__(*args, **kwargs)`
`  File "C:\[...]\Arc_Palette\.venv\Lib\site-packages\ttkbootstrap\style.py", line 5169, in __init__wrapper`
`    func(self, *args, **kwargs)`
`  File "C:\[...]\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 2775, in __init__`
`    Widget.__init__(self, master, 'canvas', cnf, kw)`
`  File "C:[...]\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 2659, in __init__`
`    self.tk.call(`
`_tkinter.TclError: bad screen distance "200.0"`

**Comment by valk-ryx** [comment]
That usually means you aren't using a venv, that's what caused it for me.

**Comment by Andrew-J-Larson** [comment]
There was a script file (or it might have been in the advanced instructions) that I had forgotten to use the `call` command in for using venv, it was likely related to that, which I already fixed with the added support for executable creation.

But it shouldn't be an issue with the latest version

**Comment by valk-ryx** [comment]
Fixed in latest update

**Comment by Andrew-J-Larson** [comment]
However, the `_tkinter.TclError: bad screen distance "200.0"` issue is something we've been seeing still persist for some users.

@SummaCristian do you use a different main language on your computer? Also, do you have other languages installed on the computer that you swap between?

**Comment by SummaCristian** [comment]
My computer is set to Italian and it's still giving me the same error even in v1.9, however I just tried switching to English (United States) as the viewing language and it now works without any issue, so it has something to do with the system language.

**Comment by Andrew-J-Larson** [comment]
> My computer is set to Italian and it's still giving me the same error even in v1.9, however I just tried switching to English (United States) as the viewing language and it now works without any issue, so it has something to do with the system language.

Yeah that confirms my sneaking suspicion. We'll see what we can do about fixing that in the next update.

**Comment by Andrew-J-Larson** [comment]
@SummaCristian https://github.com/neurokitti/Arc_Palette/releases/tag/v0.2.1-beta should fix the issue.

**Comment by SummaCristian** [comment]
> @SummaCristian https://github.com/neurokitti/Arc_Palette/releases/tag/v0.2.1-beta should fix the issue.

It does indeed, great job
